=== ghrabla/ENSA_LPSIC_TPS/tps_code_1/tp_xml/bibliographie.dtd
<!ELEMENT bibliographie (publication+)>
<!ELEMENT publication (titre, auteurs, pages, annee)>
<!ATTLIST publication type (article|conference) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (auteur+)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT pages (page+)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT annee (#PCDATA)>

=== ghrabla/ENSA_LPSIC_TPS/tps_code_1/tp_xml/bibliographie.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="bibliographie.css"?>
<!DOCTYPE bibliographie SYSTEM "bibliographie.dtd">
<bibliographie>
  <publication type="article">
    <titre>Analyse des réseaux IoT</titre>
    <auteurs>
      <auteur>Nadia El Amrani</auteur>
      <auteur>Omar Saidi</auteur>
    </auteurs>
    <pages>
      <page>12-24</page>
    </pages>
    <annee>2022</annee>
  </publication>
  <publication type="conference">
    <titre>Optimisation des systèmes distribués</titre>
    <auteurs>
      <auteur>Hajar Lahlou</auteur>
      <auteur>Yassine Bekkali</auteur>
      <auteur>Imane Chraibi</auteur>
    </auteurs>
    <pages>
      <page>101-110</page>
      <page>201-205</page>
    </pages>
    <annee>2024</annee>
  </publication>
</bibliographie>
