=== ghrabla/ENSA_LPSIC_TPS/tps_code_1/tp_xml/liste-interpretes.dtd
<!ELEMENT liste-interpretes (interprete+)>
<!ELEMENT interprete (nom, prenom, genre?, pays?)>
<!ATTLIST interprete id ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT pays (#PCDATA)>

=== ghrabla/ENSA_LPSIC_TPS/tps_code_1/tp_xml/Liste-interpretes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE liste-interpretes SYSTEM "liste-interpretes.dtd">
<liste-interpretes>
  <interprete id="i1">
    <nom>Benali</nom>
    <prenom>Karim</prenom>
    <genre>Pop</genre>
    <pays>Maroc</pays>
  </interprete>
  <interprete id="i2">
    <nom>Moreau</nom>
    <prenom>Claire</prenom>
    <genre>Jazz</genre>
    <pays>France</pays>
  </interprete>
</liste-interpretes>
